# Generated by Django 3.1.6 on 2021-02-08 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('about', models.TextField(max_length=256)),
                ('content', models.TextField(max_length=1024)),
                ('author', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='upload/')),
                ('publish', models.DateTimeField(default='2021-02-08 21:57:20')),
                ('source', models.URLField(null=True)),
            ],
        ),
    ]
