# Generated by Django 3.1.6 on 2021-02-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default='2021-02-09 15:33:53'),
        ),
    ]
