# Generated by Django 3.1.6 on 2021-02-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210209_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default='2021-02-09 15:42:22'),
        ),
    ]
