# Generated by Django 3.1.6 on 2021-02-10 22:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20210210_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 10, 22, 4, 11, 161009)),
        ),
    ]
