# Generated by Django 3.1.6 on 2021-02-22 19:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20210217_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='single_image',
            field=models.FileField(null=True, upload_to='demo/'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 22, 19, 59, 26, 118493)),
        ),
    ]
